### ISSUE TITLE
EFS Mount - Unmount hung

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/github-actions-deploy-docker-to-ec2#110]
Sometimes EFS Mounting and unmountig fails or get stuck. We should make the ansible scripts more resilient if possible

**Comment by PhillypHenning** [comment]
Can you link an example action failure to this? 
I'll look into it

**Comment by LeoDiazL** [comment]
Logic fixed in commons. Same approach, but we can now _detect_ when we need to unmount, mount, etc.
