### ISSUE TITLE
Add a termination protection option for EC2 instance

### ISSUE THREAD

**Issue by armab** [bitovi/github-actions-deploy-docker-to-ec2#119]
The action can destroy the existing instance on the upstream AMI update.
If you have data on the instance, - it'll be destroyed if you don't pin the AMI:

```
# aws_instance.server must be replaced
  -/+ resource "aws_instance" "server" {
        ~ ami                                  = "ami-007855ac798b5175e" -> "ami-0f1bae6c3bedcc3b5" # forces replacement
```
https://github.com/bitovi/chaoss-config/actions/runs/4690427226/jobs/8313499540#step:2:1107

This is one of our :-1: approaches in general, - when we encourage running `terraform apply` by default with BitOps without reviewing the `plan`, as discussed in the past.

Solutions ordered by difficulty when using gha-deploy-docker-to-ec2:
* pin AMI (easiest)
* add instance protection (additional safety net feature)
* use EFS (+infra complexity)
* rework our workflows to use *PRs* for `terraform plan`, and `terraform apply` on *merge* (best practice for the future)

---

With that, it's worth recommending in the README the action users to pin the AMI (though it's not much user-friendly).
Also, it wouldn't be too hard to add an additional `ec2_enable_instance_termination_protection: true` or similar flag (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html) as an additional safety net.

**Comment by LeoDiazL** [comment]
Will implement two features in commons. 
- lifecycle ignore ami - Makes terraform not to update the EC2 instance if a new ami-id is found.
- allow option for ec2 instance protection

**Comment by LeoDiazL** [comment]
Done in commons

- AMI lifecycle is done. 
- Terraform instance protection only block api termination, termination only possible through GUI without any protection. Complicating things. Almost meaningless. Added a boolean check in the action to avoid deletion, but it's just at an action-level protection. 
- Root volume preserve - Makes the disk non disposable after termination. 

Next steps
- Split EFS and RDS creation at a Terraform level, making EC2, RDS and EFS independent one from each other.
