### ISSUE TITLE
`docker_full_cleanup` should be `true` by default

### ISSUE THREAD

**Issue by DetachHead** [bitovi/github-actions-deploy-docker-to-ec2#156]
in my opinion, `docker_full_cleanup` should be `true` by default, because otherwise after a few deployments the instance will run out of disk space.

**Comment by LeoDiazL** [comment]
@DetachHead I think it does makes sense in most of the cases, but ...

```
docker compose down --remove-orphans --rmi all --volumes
docker system prune --all --force --volumes
docker volume prune --all --force
```

We are doing something destructive, so I prefer the conservative take here.
