### ISSUE TITLE
Allow specifying a aws secrets manager key to pull secret .env file

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/github-actions-deploy-docker-to-ec2#20]
current `.env` file is managed via the calling repo's Repository secrets via a `DOT_ENV` secret.

It would be nice to allow configuration to point to a secret name in AWS Secrets Manager to pull the secret from instead

**Comment by LeoDiazL** [comment]
Love the idea. 
One of the easy ways to manage secrets is by creating a json. 
How do we manage which values are being passed and how do we prioritize them?
