### ISSUE TITLE
tf state bucket name can exceed bucket name limit

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/github-actions-deploy-docker-to-ec2#23]
s3 bucket name length limit is 63 chars.
if the generated resource identifier is, for example, 60 characters, then the tf state bucket will append `-tf-state` and will be longer than the limit.

Example:
`bitovi-devops-holiday-2022-training-test-action-app-subdir`
length is 58, so it does not get shortened because of this code: https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/main/operations/_scripts/generate/shorten_identifier.sh#L11

the bucket would be called: `bitovi-devops-holiday-2022-training-test-action-app-subdir-tf-state` (67 characters) which is longer than the limit.

to fix: we could remove the appending of `-tf-state` here: https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/main/operations/_scripts/generate/generate_tf_state_bucket.sh#L8
However, this would be a breaking change, so we'd need an upgrade guide like:
- if you upgrade with a repo that already has a state bucket (i.e. already has been deployed), you'll need to set `aws_resource_identifier` to be what it was previously

**Comment by mickmcgrath13** [comment]
What I recommend is:

1. update [this](https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/main/operations/_scripts/generate/generate_tf_state_bucket.sh#L8) to say `-tf` (instead of `-tf-state`)
2. add migration docs to go from 0.3.* to 0.4.* (or whatever version we land on for this update) that if you already have a deployed app, you’ll need to specify tf_state_bucket in your action call to be the value of the previously generated bucket name (i.e. `${aws_resource_identifier}-tf-state`)

**Comment by mickmcgrath13** [comment]
Another option (based on internal discussion):
- Add a check to the identifier and report if the generated identifier is too large (this addresses the bug above)

The error would need to check specifically for `aws_resource_identifiers` generated that are 55 characters or more (`55 + "-tf-state".length = 64`) and show an error if that's the case.

This solves two problems;
- Unclear errors
- Attempting to create resources we know won’t work

If this happens, the only way for a user to bypass this problem is to specify a custom `aws_resource_identifier` that is 54 characters or less so that the appending of `-tf-state` will not exceed the bucket name limit.

**Comment by LeoDiazL** [comment]
We might want to catch this before reaching the bash script to create the bucket, but after merger of #26 this should be caught.

**Comment by mickmcgrath13** [comment]
Let's use this ticket to outline the need for functionality to not have our automation put users in a position where the bucket is too long simply by its use (i.e. the adding of `-tf-state` described in the initial description of this issue).

https://github.com/bitovi/github-actions-deploy-docker-to-ec2/pull/26 provides some good error handling so users know what's happening.  Next (via this issue), we need to decide how to fix our generation scripts so that users aren't experiencing the error in the first place.
