### ISSUE TITLE
Delete tf-state bucket once destroyed

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/github-actions-deploy-docker-to-ec2#27]
Should we delete the bucket if the stack-action is set to destroy?
Should we add another variable to handle deletion? 

Something like this should do it, we could add this in the after Terraform scripts.
```
aws s3 rb s3://$TF_STATE_BUCKET --force
```

**Comment by mickmcgrath13** [comment]
imo, we'd delete the bucket if stack-action is set to destroy.  any caveats you can think of with that approach?  can you think of a use case for a dedicated variable?

we could always implement it within `stack-action: destroy` and then break out a new var if a viable situation arises.
