### ISSUE TITLE
Add support for TF managed database and cache

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/github-actions-deploy-docker-to-ec2#53]
Support data (RDS, elasticache, etc) via Terraform (toggles in the action for things like `use_postgres` and then output the postgres url along with the "vm successfully deployed" message

**Comment by LeoDiazL** [comment]
To be done in commons

Split EFS, RDS and EC2 creations in different terraform runs, making each one independent from the other. Still a WIP.
