### ISSUE TITLE
Make certs available for containers

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/github-actions-deploy-docker-to-ec2#75]
Need to provide cert and key to host ssl connections

**Comment by LeoDiazL** [comment]
AWS Generated Certificates are not downloadable. 
Might need to add the option to upload owned certificates.

**Comment by sostenesapollo** [comment]
I want to set ssl in the running ec2 instance, is that possible ? to access `https`

**Comment by sostenesapollo** [comment]
@LeoDiazL any update ?

**Comment by LeoDiazL** [comment]
Hi @sostenesapollo !

Thanks for reaching out and expressing your interest in this GitHub Action! 
At this moment, certificate creation and usage is only available with domains managed with Route53. 

More info on the required inputs [here](https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/main/README.md#certificate-inputs)
More info on the the requirements [here](https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/main/README.md#certificates---only-for-aws-managed-domains-with-route53).

If your scenario is somehow different, we'd be happy to help you with the functionality you're looking for. However, we'll need more details on what you're specifically looking for so we can get a better understanding of your needs.

Once we have more information, we'll prioritize it based on our current goals and see how we can integrate it into our future plans. Please keep in mind that I can't guarantee when it will be implemented.

Thanks again for your interest and I look forward to hearing back from you.
